import cv2
from djitellopy import Tello
import time

# Initialize the primary Tello controller module
drone = Tello()

# Establish UDP control and telemetry sockets over the network interface
drone.connect()
print(f"Pre-flight Diagnostics - Battery Capacity: {drone.get_battery()}%")


# [LOGIC] streamon() sends a raw text command to port 8889. 
# The drone's onboard firmware intercepts this and starts broadcasting a live, 
# compressed H.264 video stream via UDP packets targeting your local machine's port 11111.
drone.streamon()


# [CONCEPT] get_frame_read() initializes a background thread pool inside djitellopy.
# This dedicated thread continuously listens to network port 11111, decodes the incoming
# compressed raw UDP video packets using PyAV/FFmpeg, and populates an internal memory buffer
# with the most recent uncompressed image frame arrays.
frame_reader = drone.get_frame_read()
print("Initialization Complete. Stream Window Active. Press 'q' to safely exit.")
while True:
    # [CONCEPT] .frame accesses the latest decoded image frame array from the background thread buffer.
    # The frame is retrieved as a multidimensional NumPy array matching the drone's native camera output.
    frame = frame_reader.frame
    

    # [CV2 CONCEPT] imshow() handles GUI rendering. It creates a local desktop display window
    # named "Tello Live Video Feed" and flushes the current BGR NumPy pixel matrix onto it. 
    # Running this continuously inside a while loop handles frame updates to create fluid video.

    cv2.imshow("Tello Live Video Feed", frame)
    # [CV2 LOGIC: Frame Rate Control & Keyboard Event I/O]
    # waitKey(1) pauses code execution for exactly 1 millisecond to listen for keyboard events.
    # This delay is strictly required; without it, the cv2 GUI thread cannot process window paint cycles.
    # The bitwise mask '& 0xFF' isolates the lowest 8 bits of the keypress code to verify compatibility.
    # ord('q') returns the ASCII value of character 'q' (113) to check if the user triggered an exit.

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
# [CLEANUP] Close and release all native GUI desktop display windows generated by OpenCV

cv2.destroyAllWindows()

# [CLEANUP] Send a termination signal to the drone to shut down the H.264 video broadcast.
# This prevents network socket leakage and lowers the drone's CPU thermal throttling limits.
drone.streamoff()